#! /bin/sh

path="$1"

if [ -z "$path" ]; then
    echo "need path" >&2
    exit 1
fi

presentation_basename=$(basename "$path")

mkdir -p "$path"

rsync --exclude instantiate --exclude=.git -av ./ "$path";
git -C "$path" init
git -C "$path" add -A
git -C "$path" commit -m 'initial import'
ln -sf "$path" ~/www/"$presentation_basename"
